name: my_blood
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  auto_route: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  syncfusion_flutter_charts: ^21.1.41
  flutter_bloc: ^8.1.2
  fpdart: ^0.5.0
  uuid: ^3.0.7
  easy_localization: ^3.0.2-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  auto_route_generator: ^6.1.0
  build_runner: ^2.4.1
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
